// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3n69amusSnUqB1rzDOkv-MXw6ac01e8',
    appId: '1:493196103679:web:bc0eca400fc3279cfc21ca',
    messagingSenderId: '493196103679',
    projectId: 'seventyfiveyou',
    authDomain: 'seventyfiveyou.firebaseapp.com',
    storageBucket: 'seventyfiveyou.appspot.com',
    measurementId: 'G-J97D103HS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5WeFRSyp7AaPT_NFEBX9B-BpjxVRpPs',
    appId: '1:493196103679:android:54f74f036e307bdcfc21ca',
    messagingSenderId: '493196103679',
    projectId: 'seventyfiveyou',
    storageBucket: 'seventyfiveyou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkzSRisydIpy1cYxpyj5zcxz4ljyDBqk0',
    appId: '1:493196103679:ios:cf6ea656670ed745fc21ca',
    messagingSenderId: '493196103679',
    projectId: 'seventyfiveyou',
    storageBucket: 'seventyfiveyou.appspot.com',
    iosBundleId: 'com.example.seventyFiveHard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkzSRisydIpy1cYxpyj5zcxz4ljyDBqk0',
    appId: '1:493196103679:ios:f96d77b2efa3f1d9fc21ca',
    messagingSenderId: '493196103679',
    projectId: 'seventyfiveyou',
    storageBucket: 'seventyfiveyou.appspot.com',
    iosBundleId: 'com.example.seventyFiveHard.RunnerTests',
  );
}
